model_params:
  model_type: "YOLOv7"
  model_name: "./pt/yolov7.pt"
  img_size: 640
  device: "cpu"
  data: "./dataset/sample/sample.yaml"
  optimizer: "adam"
  epochs: 50
  batch_size: 4
  hyp: "./hyp/hyp.scratch.custom.yaml"
  cfg: "./cfg/yolov7-animal_sample.yaml"
  wandb_token: "ec5f8b774518ef76ccba414d42f6e689fbc59a03"

training_params:
  batch_size: 16
  learning_rate: 0.01
