model_params:
  model_type: "RTDETR"
  model_name: "./pt/rtdetr-l.pt"
  img_size: 640
  device: "cpu"
  data: "./dataset/sample/sample.yaml"
  optimizer: "Adam"
  epochs: 50
  batch_size: 4
  hyp: "./hpy/hyp.scratch.custom.yaml"
  cfg: "./cfg/yolov7-animal_sample.yaml"
  wandb_token: "ec5f8b774518ef76ccba414d42f6e689fbc59a03"

training_params:
  learning_rate: 0.01
